spring:
  application:
    name: Inventory Management System

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret:
  expiration: 3600000