spring:
  application:
    name: Inventory Management System

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  profiles:
    active: dev

jwt:
  secret: abCDeFGhIJklMNopQRstUVwxYZ1234567890abcdEFGHijkl
  expiration-ms: 86400000
